name: "Release Artifacts"
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: read
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          version: 0.12.0-dev.790+ad6f8e3a5
      - name: Build
        run: ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            zig-out/archives/*
          
